"""add inventory_items table

Revision ID: 7dd95fe06039
Revises: phase5_audit_hardening
Create Date: 2026-08-10 19:10:23.702972
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7dd95fe06039'
down_revision: Union[str, None] = 'phase5_audit_hardening'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('drug_id', sa.UUID(), nullable=False),
    sa.Column('stock_level', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('tenant_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.drug_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_index(op.f('ix_inventory_items_drug_id'), 'inventory_items', ['drug_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_tenant_id'), 'inventory_items', ['tenant_id'], unique=False)
    
    # Enable RLS
    op.execute("ALTER TABLE inventory_items ENABLE ROW LEVEL SECURITY;")
    op.execute("""
        CREATE POLICY tenant_isolation_inventory ON inventory_items
        FOR ALL
        USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation_inventory ON inventory_items;")
    op.drop_index(op.f('ix_inventory_items_tenant_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_drug_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
