"""audit_log_and_force_rls

Revision ID: 8bde7c490701
Revises: c89fa4cf264b
Create Date: 2026-08-10 13:44:41.707292
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8bde7c490701'
down_revision: Union[str, None] = 'c89fa4cf264b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ab_test_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ab_tests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('events', sa.Column('payload_hash', sa.String(length=64), nullable=True))
    op.add_column('events', sa.Column('prev_hash', sa.String(length=64), nullable=True))
    op.add_column('events', sa.Column('actor_id', sa.UUID(), nullable=True))
    op.add_column('events', sa.Column('source_ip', sa.String(length=45), nullable=True))
    op.add_column('events', sa.Column('user_agent', sa.String(length=200), nullable=True))
    op.alter_column('events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'order_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('sessions_tenant_id_fkey', 'sessions', type_='foreignkey')
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
    for tab in ('customers', 'orders', 'order_items', 'drugs', 'events', 'sessions'):
        op.execute(f"ALTER TABLE {tab} FORCE ROW LEVEL SECURITY;")
    
    op.execute("""
    CREATE OR REPLACE FUNCTION current_user_tenant_id()
    RETURNS uuid
    LANGUAGE sql
    VOLATILE
    SECURITY DEFINER
    SET search_path = public
    AS $$
      SELECT tenant_id FROM customers WHERE auth_user_id = auth.uid() LIMIT 1;
    $$;
    """)
    
    op.execute("ALTER TABLE events ENABLE ROW LEVEL SECURITY;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_events ON events;")
    op.execute("""
        CREATE POLICY tenant_isolation_events ON events
          FOR ALL USING (
            EXISTS(SELECT 1 FROM sessions s JOIN customers c ON c.customer_id = s.customer_id
                   WHERE s.session_id = events.session_id AND c.tenant_id = current_user_tenant_id())
          );
    """)

    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    
    op.execute("""
    CREATE OR REPLACE FUNCTION events_chains() RETURNS TRIGGER AS $$
    DECLARE
      latest_hash text;
    BEGIN
      SELECT payload_hash FROM events e
      WHERE e.session_id = NEW.session_id
      ORDER BY e.timestamp DESC LIMIT 1 INTO latest_hash;
      NEW.prev_hash := COALESCE(latest_hash, '0000');
      NEW.payload_hash := encode(
        digest(
          COALESCE(NEW.payload::text, '') || '|' || NEW.prev_hash || '|' || COALESCE(NEW.actor_id::text,''),
          'sha256'
        ), 'hex'
      );
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;
    """)
    op.execute("DROP TRIGGER IF EXISTS events_chain ON events;")
    op.execute("""
    CREATE TRIGGER events_chain BEFORE INSERT ON events
      FOR EACH ROW EXECUTE FUNCTION events_chains();
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key('sessions_tenant_id_fkey', 'sessions', 'tenants', ['tenant_id'], ['tenant_id'])
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'order_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('events', 'user_agent')
    op.drop_column('events', 'source_ip')
    op.drop_column('events', 'actor_id')
    op.drop_column('events', 'prev_hash')
    op.drop_column('events', 'payload_hash')
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ab_tests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ab_test_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
    op.execute("DROP TRIGGER IF EXISTS events_chain ON events;")
    op.execute("DROP FUNCTION IF EXISTS events_chains();")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_events ON events;")
    
    for tab in ('customers', 'orders', 'order_items', 'drugs', 'events', 'sessions'):
        op.execute(f"ALTER TABLE {tab} NO FORCE ROW LEVEL SECURITY;")
