"""Add tenant settings

Revision ID: b7a790f21e4b
Revises: phase6_chain_backfill
Create Date: 2026-08-11 00:12:10.110992
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b7a790f21e4b'
down_revision: Union[str, None] = 'phase6_chain_backfill'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('ai_review_mode', sa.Boolean(), nullable=False),
    sa.Column('enterprise_notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.alter_column('contact_messages', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('contact_messages', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('contact_messages', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('contact_messages', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_contact_messages_tenant_id'), 'contact_messages', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('contact_messages_customer_id_fkey'), 'contact_messages', type_='foreignkey')
    op.create_foreign_key(None, 'contact_messages', 'tenants', ['tenant_id'], ['tenant_id'])
    op.drop_column('contact_messages', 'status')
    op.alter_column('events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('events_event_seq_idx'), table_name='events')
    op.create_index(op.f('ix_events_event_seq'), 'events', ['event_seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_event_seq'), table_name='events')
    op.create_index(op.f('events_event_seq_idx'), 'events', ['event_seq'], unique=False)
    op.alter_column('events', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('contact_messages', sa.Column('status', sa.TEXT(), server_default=sa.text("'new'::text"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contact_messages', type_='foreignkey')
    op.create_foreign_key(op.f('contact_messages_customer_id_fkey'), 'contact_messages', 'users', ['customer_id'], ['id'], referent_schema='auth', ondelete='SET NULL')
    op.drop_index(op.f('ix_contact_messages_tenant_id'), table_name='contact_messages')
    op.alter_column('contact_messages', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('contact_messages', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('contact_messages', 'last_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('contact_messages', 'first_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_table('tenant_settings')
    # ### end Alembic commands ###
